--Deployment script for methods in assembly: Clr
--Autogenerated at: 31/08/2010 11:24:08

--About to drop and recreate CLR Methods and Aggregates
if exists(select name from sys.objects where name = 'fnLPad')
DROP FUNCTION [fnLPad]
GO

CREATE FUNCTION [fnLPad](@aStr nvarchar(256), @aTotalWidth int, @aPaddingChar nvarchar(1))
RETURNS nvarchar(256)
AS
EXTERNAL NAME [Clr].[StringFuncs].[fnLPad]
GO

if exists(select name from sys.objects where name = 'fnRPad')
DROP FUNCTION [fnRPad]
GO

CREATE FUNCTION [fnRPad](@aStr nvarchar(256), @aTotalWidth int, @aPaddingChar nvarchar(1))
RETURNS nvarchar(256)
AS
EXTERNAL NAME [Clr].[StringFuncs].[fnRPad]
GO

if exists(select name from sys.objects where name = 'fnTrim')
DROP FUNCTION [fnTrim]
GO

CREATE FUNCTION [fnTrim](@aStr nvarchar(1024))
RETURNS nvarchar(1024)
AS
EXTERNAL NAME [Clr].[StringFuncs].[fnTrim]
GO

if exists(select name from sys.objects where name = 'fnTrimFull')
DROP FUNCTION [fnTrimFull]
GO

CREATE FUNCTION [fnTrimFull](@aStr nvarchar(1024))
RETURNS nvarchar(1024)
AS
EXTERNAL NAME [Clr].[StringFuncs].[fnTrimFull]
GO

if exists(select name from sys.objects where name = 'fnRegexMatch')
DROP FUNCTION [fnRegexMatch]
GO

CREATE FUNCTION [fnRegexMatch](@aStr nvarchar(256), @Pattern nvarchar(128))
RETURNS bit
AS
EXTERNAL NAME [Clr].[StringFuncs].[fnRegexMatch]
GO

if exists(select * from sys.objects where name = 'fnList')
DROP AGGREGATE [fnList]
GO

CREATE AGGREGATE [fnList](@value nvarchar(128), @Separator nvarchar(1))
RETURNS nvarchar(max)
EXTERNAL NAME [Clr].[fnList]
GO

if exists(select name from sys.objects where name = 'fnGetDigitStream')
DROP FUNCTION [fnGetDigitStream]
GO

CREATE FUNCTION [fnGetDigitStream](@aStream nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnGetDigitStream]
GO

if exists(select name from sys.objects where name = 'fnValidIBAN')
DROP FUNCTION [fnValidIBAN]
GO

CREATE FUNCTION [fnValidIBAN](@aIBAN nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnValidIBAN]
GO

if exists(select name from sys.objects where name = 'fnFormatIBANElectronicVersion')
DROP FUNCTION [fnFormatIBANElectronicVersion]
GO

CREATE FUNCTION [fnFormatIBANElectronicVersion](@aIBAN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatIBANElectronicVersion]
GO

if exists(select name from sys.objects where name = 'fnFormatIBANPaperVersion')
DROP FUNCTION [fnFormatIBANPaperVersion]
GO

CREATE FUNCTION [fnFormatIBANPaperVersion](@aIBAN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatIBANPaperVersion]
GO

if exists(select name from sys.objects where name = 'fnValidBBAN')
DROP FUNCTION [fnValidBBAN]
GO

CREATE FUNCTION [fnValidBBAN](@aBBAN nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnValidBBAN]
GO

if exists(select name from sys.objects where name = 'fnFormatBBANElectronicVersion')
DROP FUNCTION [fnFormatBBANElectronicVersion]
GO

CREATE FUNCTION [fnFormatBBANElectronicVersion](@aBBAN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatBBANElectronicVersion]
GO

if exists(select name from sys.objects where name = 'fnFormatBBANPaperVersion')
DROP FUNCTION [fnFormatBBANPaperVersion]
GO

CREATE FUNCTION [fnFormatBBANPaperVersion](@aBBAN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatBBANPaperVersion]
GO

if exists(select name from sys.objects where name = 'fnBBAN2IBAN')
DROP FUNCTION [fnBBAN2IBAN]
GO

CREATE FUNCTION [fnBBAN2IBAN](@aBBAN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnBBAN2IBAN]
GO

if exists(select name from sys.objects where name = 'fnIBAN2BBAN')
DROP FUNCTION [fnIBAN2BBAN]
GO

CREATE FUNCTION [fnIBAN2BBAN](@aIBAN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnIBAN2BBAN]
GO

if exists(select name from sys.objects where name = 'fnValidKBO')
DROP FUNCTION [fnValidKBO]
GO

CREATE FUNCTION [fnValidKBO](@aKBO nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnValidKBO]
GO

if exists(select name from sys.objects where name = 'fnFormatKBOElectronicVersion')
DROP FUNCTION [fnFormatKBOElectronicVersion]
GO

CREATE FUNCTION [fnFormatKBOElectronicVersion](@aKBO nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatKBOElectronicVersion]
GO

if exists(select name from sys.objects where name = 'fnFormatKBOPaperVersion')
DROP FUNCTION [fnFormatKBOPaperVersion]
GO

CREATE FUNCTION [fnFormatKBOPaperVersion](@aKBO nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatKBOPaperVersion]
GO

if exists(select name from sys.objects where name = 'fnValidRRN')
DROP FUNCTION [fnValidRRN]
GO

CREATE FUNCTION [fnValidRRN](@aRRN nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnValidRRN]
GO

if exists(select name from sys.objects where name = 'fnFormatRRNElectronicVersion')
DROP FUNCTION [fnFormatRRNElectronicVersion]
GO

CREATE FUNCTION [fnFormatRRNElectronicVersion](@aRRN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatRRNElectronicVersion]
GO

if exists(select name from sys.objects where name = 'fnFormatRRNPaperVersion')
DROP FUNCTION [fnFormatRRNPaperVersion]
GO

CREATE FUNCTION [fnFormatRRNPaperVersion](@aRRN nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatRRNPaperVersion]
GO

if exists(select name from sys.objects where name = 'fnGetBirthDateFromRRN')
DROP FUNCTION [fnGetBirthDateFromRRN]
GO

CREATE FUNCTION [fnGetBirthDateFromRRN](@aRRN nvarchar(64))
RETURNS datetime
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnGetBirthDateFromRRN]
GO

if exists(select name from sys.objects where name = 'fnGetSexeFromRRN')
DROP FUNCTION [fnGetSexeFromRRN]
GO

CREATE FUNCTION [fnGetSexeFromRRN](@aRRN nvarchar(64))
RETURNS int
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnGetSexeFromRRN]
GO

if exists(select name from sys.objects where name = 'fnValidRSZ')
DROP FUNCTION [fnValidRSZ]
GO

CREATE FUNCTION [fnValidRSZ](@aRSZ nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnValidRSZ]
GO

if exists(select name from sys.objects where name = 'fnTemporaryRSZ')
DROP FUNCTION [fnTemporaryRSZ]
GO

CREATE FUNCTION [fnTemporaryRSZ](@aRSZ nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnTemporaryRSZ]
GO

if exists(select name from sys.objects where name = 'fnFormatRSZElectronicVersion')
DROP FUNCTION [fnFormatRSZElectronicVersion]
GO

CREATE FUNCTION [fnFormatRSZElectronicVersion](@aRSZ nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatRSZElectronicVersion]
GO

if exists(select name from sys.objects where name = 'fnFormatRSZPaperVersion')
DROP FUNCTION [fnFormatRSZPaperVersion]
GO

CREATE FUNCTION [fnFormatRSZPaperVersion](@aRSZ nvarchar(64))
RETURNS nvarchar(64)
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnFormatRSZPaperVersion]
GO

if exists(select name from sys.objects where name = 'fnValidVAT')
DROP FUNCTION [fnValidVAT]
GO

CREATE FUNCTION [fnValidVAT](@VATNbr nvarchar(64))
RETURNS bit
AS
EXTERNAL NAME [Clr].[AdministrativeUtils].[fnValidVAT]
GO

if exists(select name from sys.objects where name = 'fnDateTime_Create')
DROP FUNCTION [fnDateTime_Create]
GO

CREATE FUNCTION [fnDateTime_Create](@aYear int, @aMonth int, @aDay int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_Create]
GO

if exists(select name from sys.objects where name = 'fnDateTime_FirstOfMonth')
DROP FUNCTION [fnDateTime_FirstOfMonth]
GO

CREATE FUNCTION [fnDateTime_FirstOfMonth](@aYear int, @aMonth int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_FirstOfMonth]
GO

if exists(select name from sys.objects where name = 'fnDateTime_LastOfMonth')
DROP FUNCTION [fnDateTime_LastOfMonth]
GO

CREATE FUNCTION [fnDateTime_LastOfMonth](@aYear int, @aMonth int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_LastOfMonth]
GO

if exists(select name from sys.objects where name = 'fnDateTime_FirstOfYear')
DROP FUNCTION [fnDateTime_FirstOfYear]
GO

CREATE FUNCTION [fnDateTime_FirstOfYear](@aYear int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_FirstOfYear]
GO

if exists(select name from sys.objects where name = 'fnDateTime_LastOfYear')
DROP FUNCTION [fnDateTime_LastOfYear]
GO

CREATE FUNCTION [fnDateTime_LastOfYear](@aYear int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_LastOfYear]
GO

if exists(select name from sys.objects where name = 'fnDateTime_StripTime')
DROP FUNCTION [fnDateTime_StripTime]
GO

CREATE FUNCTION [fnDateTime_StripTime](@aDateTime datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_StripTime]
GO

if exists(select name from sys.objects where name = 'fnDateTime_StripHour')
DROP FUNCTION [fnDateTime_StripHour]
GO

CREATE FUNCTION [fnDateTime_StripHour](@aDateTime datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_StripHour]
GO

if exists(select name from sys.objects where name = 'fnDateTime_StripMinute')
DROP FUNCTION [fnDateTime_StripMinute]
GO

CREATE FUNCTION [fnDateTime_StripMinute](@aDateTime datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_StripMinute]
GO

if exists(select name from sys.objects where name = 'fnDateTime_Today')
DROP FUNCTION [fnDateTime_Today]
GO

CREATE FUNCTION [fnDateTime_Today]()
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_Today]
GO

if exists(select name from sys.objects where name = 'fnDateTime_Yesterday')
DROP FUNCTION [fnDateTime_Yesterday]
GO

CREATE FUNCTION [fnDateTime_Yesterday]()
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_Yesterday]
GO

if exists(select name from sys.objects where name = 'fnDateTime_Tomorrow')
DROP FUNCTION [fnDateTime_Tomorrow]
GO

CREATE FUNCTION [fnDateTime_Tomorrow]()
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_Tomorrow]
GO

if exists(select name from sys.objects where name = 'fnDateTime_DaysInMonth')
DROP FUNCTION [fnDateTime_DaysInMonth]
GO

CREATE FUNCTION [fnDateTime_DaysInMonth](@aYear int, @aMonth int)
RETURNS int
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_DaysInMonth]
GO

if exists(select name from sys.objects where name = 'fnDateTime_MaxDate')
DROP FUNCTION [fnDateTime_MaxDate]
GO

CREATE FUNCTION [fnDateTime_MaxDate](@aDateTime1 datetime, @aDateTime2 datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_MaxDate]
GO

if exists(select name from sys.objects where name = 'fnDateTime_MinDate')
DROP FUNCTION [fnDateTime_MinDate]
GO

CREATE FUNCTION [fnDateTime_MinDate](@aDateTime1 datetime, @aDateTime2 datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_MinDate]
GO

if exists(select name from sys.objects where name = 'fnDateTime_AddWorkingDays')
DROP FUNCTION [fnDateTime_AddWorkingDays]
GO

CREATE FUNCTION [fnDateTime_AddWorkingDays](@_aDateTime datetime, @_aNrWorkingDays int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_AddWorkingDays]
GO

if exists(select name from sys.objects where name = 'fnDateTime_WorkingDaysBetween')
DROP FUNCTION [fnDateTime_WorkingDaysBetween]
GO

CREATE FUNCTION [fnDateTime_WorkingDaysBetween](@_aStartDate datetime, @_aEndDate datetime)
RETURNS int
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_WorkingDaysBetween]
GO

if exists(select name from sys.objects where name = 'fnDateTime_NextWorkingDay')
DROP FUNCTION [fnDateTime_NextWorkingDay]
GO

CREATE FUNCTION [fnDateTime_NextWorkingDay](@aDate datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_NextWorkingDay]
GO

if exists(select name from sys.objects where name = 'fnDateTime_PreviousWorkingDay')
DROP FUNCTION [fnDateTime_PreviousWorkingDay]
GO

CREATE FUNCTION [fnDateTime_PreviousWorkingDay](@aDate datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_PreviousWorkingDay]
GO

if exists(select name from sys.objects where name = 'fnCalcAge')
DROP FUNCTION [fnCalcAge]
GO

CREATE FUNCTION [fnCalcAge](@aBirthDate datetime, @aDate datetime)
RETURNS int
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnCalcAge]
GO

if exists(select name from sys.objects where name = 'fnQuarter_Quarter')
DROP FUNCTION [fnQuarter_Quarter]
GO

CREATE FUNCTION [fnQuarter_Quarter](@aQuarter datetime)
RETURNS int
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnQuarter_Quarter]
GO

if exists(select name from sys.objects where name = 'fnDateTime_Quarter')
DROP FUNCTION [fnDateTime_Quarter]
GO

CREATE FUNCTION [fnDateTime_Quarter](@aQuarter datetime)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnDateTime_Quarter]
GO

if exists(select name from sys.objects where name = 'fnQuarter_StartDate')
DROP FUNCTION [fnQuarter_StartDate]
GO

CREATE FUNCTION [fnQuarter_StartDate](@aQuarter int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnQuarter_StartDate]
GO

if exists(select name from sys.objects where name = 'fnQuarter_EndDate')
DROP FUNCTION [fnQuarter_EndDate]
GO

CREATE FUNCTION [fnQuarter_EndDate](@aQuarter int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnQuarter_EndDate]
GO

if exists(select name from sys.objects where name = 'fnQuarter_EndDateOfYear')
DROP FUNCTION [fnQuarter_EndDateOfYear]
GO

CREATE FUNCTION [fnQuarter_EndDateOfYear](@aQuarter int)
RETURNS datetime
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnQuarter_EndDateOfYear]
GO

if exists(select name from sys.objects where name = 'fnQuarters_List')
DROP FUNCTION [fnQuarters_List]
GO

CREATE FUNCTION [fnQuarters_List](@aStartDate datetime, @aEndDate datetime)
RETURNS TABLE ([Quarter] int, StartDate date, EndDate date)
AS
EXTERNAL NAME [Clr].[TimeFunctions].[fnQuarters_List]
GO

