#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatePartialMethods
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="zetes")]
	public partial class zetesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public zetesDataContext() : 
				base(global::CreatePartialMethods.Properties.Settings.Default.zetesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public zetesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public zetesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public zetesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public zetesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UIDRoutine> UIDRoutines
		{
			get
			{
				return this.GetTable<UIDRoutine>();
			}
		}
		
		public System.Data.Linq.Table<UIDRoutineParameter> UIDRoutineParameters
		{
			get
			{
				return this.GetTable<UIDRoutineParameter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_sys_uid_routines")]
	public partial class UIDRoutine
	{
		
		private string _relation;
		
		private string _base_routine;
		
		private string _routine_name;
		
		private string _PartialMethodName;
		
		private System.Nullable<bool> _overruled;
		
		public UIDRoutine()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relation", DbType="NVarChar(128)")]
		public string relation
		{
			get
			{
				return this._relation;
			}
			set
			{
				if ((this._relation != value))
				{
					this._relation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_base_routine", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string base_routine
		{
			get
			{
				return this._base_routine;
			}
			set
			{
				if ((this._base_routine != value))
				{
					this._base_routine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_routine_name", DbType="NVarChar(128)")]
		public string routine_name
		{
			get
			{
				return this._routine_name;
			}
			set
			{
				if ((this._routine_name != value))
				{
					this._routine_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartialMethodName", DbType="NVarChar(135)")]
		public string PartialMethodName
		{
			get
			{
				return this._PartialMethodName;
			}
			set
			{
				if ((this._PartialMethodName != value))
				{
					this._PartialMethodName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overruled", DbType="Bit")]
		public System.Nullable<bool> overruled
		{
			get
			{
				return this._overruled;
			}
			set
			{
				if ((this._overruled != value))
				{
					this._overruled = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_sys_uid_routine_params")]
	public partial class UIDRoutineParameter
	{
		
		private string _relation;
		
		private string _routine_name;
		
		private string _PartialMethodName;
		
		private int _ORDINAL_POSITION;
		
		private string _CS_DECLARATION;
		
		private string _CS_PARAMETER_DESCR;
		
		private string _CS_AFTER_CALL;
		
		public UIDRoutineParameter()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relation", DbType="NVarChar(128)")]
		public string relation
		{
			get
			{
				return this._relation;
			}
			set
			{
				if ((this._relation != value))
				{
					this._relation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_routine_name", DbType="NVarChar(128)")]
		public string routine_name
		{
			get
			{
				return this._routine_name;
			}
			set
			{
				if ((this._routine_name != value))
				{
					this._routine_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartialMethodName", DbType="NVarChar(135)")]
		public string PartialMethodName
		{
			get
			{
				return this._PartialMethodName;
			}
			set
			{
				if ((this._PartialMethodName != value))
				{
					this._PartialMethodName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDINAL_POSITION", DbType="Int NOT NULL")]
		public int ORDINAL_POSITION
		{
			get
			{
				return this._ORDINAL_POSITION;
			}
			set
			{
				if ((this._ORDINAL_POSITION != value))
				{
					this._ORDINAL_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CS_DECLARATION", DbType="NVarChar(309)")]
		public string CS_DECLARATION
		{
			get
			{
				return this._CS_DECLARATION;
			}
			set
			{
				if ((this._CS_DECLARATION != value))
				{
					this._CS_DECLARATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CS_PARAMETER_DESCR", DbType="NVarChar(180)")]
		public string CS_PARAMETER_DESCR
		{
			get
			{
				return this._CS_PARAMETER_DESCR;
			}
			set
			{
				if ((this._CS_PARAMETER_DESCR != value))
				{
					this._CS_PARAMETER_DESCR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CS_AFTER_CALL", DbType="NVarChar(284)")]
		public string CS_AFTER_CALL
		{
			get
			{
				return this._CS_AFTER_CALL;
			}
			set
			{
				if ((this._CS_AFTER_CALL != value))
				{
					this._CS_AFTER_CALL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
